from enum import Enum


class Part_of_Speech(Enum):
    NOUN = "/n"
    VERB = "/v"
    ADJECTIVE = "/a"
    ADJECTIVE_SATELLITE = "/s"
    ADVERB = "/r"


class Relations(Enum):
    RelatedTo = "/r/RelatedTo"
    FormOf = "/r/FormOf"
    IsA = "/r/IsA"
    PartOf = "/r/PartOf"
    HasA = "/r/HasA"
    UsedFor = "/r/UsedFor"
    CapableOf = "/r/CapableOf"
    AtLocation = "/r/AtLocation"
    Causes = "/r/Causes"
    HasSubevent = "/r/HasSubevent"
    HasFirstSubevent = "/r/HasFirstSubevent"
    HasLastSubevent = "/r/HasLastSubevent"
    HasPrerequisite = "/r/HasPrerequisite"
    HasProperty = "/r/HasProperty"
    MotivatedByGoal = "/r/MotivatedByGoal"
    ObstructedBy = "/r/ObstructedBy"
    Desires = "/r/Desires"
    CreatedBy = "/r/CreatedBy"
    Synonym = "/r/Synonym"
    Antonym = "/r/Antonym"
    DistinctFrom = "/r/DistinctFrom"
    DerivedFrom = "/r/DerivedFrom"
    SymbolOf = "/r/SymbolOf"
    DefinedAs = "/r/DefinedAs"
    MannerOf = "/r/MannerOf"
    LocatedNear = "/r/LocatedNear"
    HasContext = "/r/HasContext"
    SimilarTo = "/r/SimilarTo"
    EtymologicallyRelatedTo = "/r/EtymologicallyRelatedTo"
    EtymologicallyDerivedFrom = "/r/EtymologicallyDerivedFrom"
    CausesDesire = "/r/CausesDesire"
    MadeOf = "/r/MadeOf"
    ReceivesAction = "/r/ReceivesAction"
    ExternalURL = "/r/ExternalURL"
